name: k8sworkshop
description: A Helm charts for Kubernetes application
version: 0.0.9
home: https://k8s.community/
sources:
  - https://github.com/dmirou/k8sworkshop
maintainers:
  - name: Kubernetes Community Authors
    email: k8s.community@gmail.com
engine: gotpl